# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

# append some arguments to the commandline;
# accepts anything listed in --help (leading dashes are optional)
# and inline comments are OK if there is 2 spaces before the '#'
[global]
  p: 80, 443                # listen on ports 80 and 443. Defaults to 8086 and 3939
  e2dsa                     # enable file indexing and filesystem scanning
  e2ts                      # and enable multimedia indexing
  # z                       # Enable zeroconf
  # qrs                     # Enable qrcode (HTTPS) (you can comma-separate arguments)
  ah-alg: argon2            # account-pw hashing algorithm
  ah-salt: %salt%           # Randomly generated salt
  th-ram-max: 1             # max memory usage (GiB) permitted by thumbnailer
  chdir: %vaultdir%         # Change working-directory to PATH before mapping volumes 
  https-only                # Only serve HTTPS
  ssl-ver: tls13            # set allowed ssl/tls versions
  cert: /root/copyparty.bundle.pem  
  logout: 1                 # logout clients after H hours of inactivity
  no-robots                 # adds http and html headers asking search engines to not index anything
  chpw                      # Allow users to change their own password
  chpw-len: 12              # Min password length
  # usernames               # Require username and password for login
  dedup                     # Enable file upload deduplication
  ipa: 192.168.1.0/24       # only accept connections from IP-addresses inside CIDR (comma-separated)


[accounts]
  admin: %hash(admin)%      # hashed admin password

[groups]
  admin: admin

[/]
  .
  accs:
    r: @acct                # All loged users can read

[/sharex]
  ./sharex
  accs:
    A: @admin               # admin group can do ALL
    r.: @acct

[/home]
  ./home
  accs:
    A: @admin

[/public]
  ./home/public
  accs:
    A: @admin
    r.: @acct

[/admin]
  ./home/admin
  accs:
    A: @admin

[/tmp]
  ./tmp
  accs:
    wG: @acct    # wG = write-upget = see your own uploads only
    A: @admin
  flags:
    d2t, fk: 4              # sets the fk (filekey) volflag to 4, meaning each file gets a 4-character accesskey
    e2ds                    # filesystem indexing is required for many of these:
    sz: 1k-3m               # accept upload only if filesize in this range
    df: 5g                  # free disk space cannot go lower than this
    vmaxb: 100g             # volume can never exceed 100 GiB
    vmaxn: 4k               # ...or 4000 files, whichever comes first
    nosub                   # must upload to toplevel folder
    lifetime: 604800        # uploads are deleted after 7 days
    maxn: 250,3600          # each IP can upload 250 files in 1 hour
    maxb: 10g,3600          # each IP can upload 10 GiB over 1 hour


